
[package]
name = "fyrox_lua"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = {workspace = true}
mlua = { version = "0.9.1", features = ["luau"] }
venial = "0.5.0"
send_wrapper = "0.6.0"
extend = "1.1.3"

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
