
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fyrox_lua = { path = "../game", default-features = false }

[features]
default = ["fyrox_lua/default"]
dylib-engine = ["fyrox_lua/dylib-engine"]
